CXX = g++
HEADER = App.h
HEADER1 = List.h
HEADER2 = Item.h
SRC = main.cpp
SRC1 = App.cpp
SRC2 = List.cpp
SRC3 = Item.cpp

shopping: ${SRC} ${SRC1} ${SRC2} ${SRC3} ${HEADER} ${HEADER1} ${HEADER2}
	${CXX} ${SRC} ${SRC1} ${SRC2} ${SRC3} -o shopping
