CXX = g++
HEADER = App.h Barbarian.h BlueMan.h Creature.h Dice.h Game.h Goblin.h Hydra.h Medusa.h
SRC = main.cpp App.cpp Barbarian.cpp BlueMan.cpp Creature.cpp Dice.cpp Game.cpp Goblin.cpp Hydra.cpp Medusa.cpp

creature1: ${HEADER} ${SRC}
	${CXX} ${SRC} -o creature1
